### ISSUE TITLE
Document how to only index the latest version

### ISSUE THREAD

**Issue by danyill** [Mogztter/antora-lunr#25]
I would like to be able to index only the latest component version (but not the master/unstable branch) for two reasons:

* Reduce index size. Many versions which are similar will quickly generate a large index (I'm not sure how well this is compressed) and I'd like to see what difference it makes if I index a single version.
* Improve UI display. The present results display with antora-lunr is a bit repetitive and just the latest version is an easy workaround for a difficult UI problem (I guess results on the same page across multiple versions should be squashed into a version tag which then itself becomes repetitive).

I think the solution is to iterate over pages and find the latest version and only index that. 

As I understand the code (which is not very well) at this point in the generation, the virtual files are already in html and so either we need a reverse lookup to extract the version for the html or we need to find this information within the web page. I thought there might be a `data-` attribute or a `meta` attribute with this information but it's not obvious to me that this currently exists.

It may also be useful to extract the prerelease information for some purposes.

**Comment by Mogztter** [comment]
The page version and the page component version are available as AsciiDoc attributes:

```js
page.asciidoc['page-version']
page.asciidoc[ 'page-component-version']
```

Ideally we should add an extension point to configure a list filters. A filter would be a function that take a page and returns true to index the page, false otherwise.

And/or we could introduce some kind of configuration.

**Comment by Mogztter** [comment]
You can have a look at https://github.com/Mogztter/antora-lunr/pull/20/files#diff-8b736585a0930c62b4c746dcf7041904R38 where I exclude/filter pages marked as "noindex".

**Comment by danyill** [comment]
Thanks @Mogztter that was most helpful :+1:. I think I learned (hopefully correctly) that I needed to gain access to the content catalog because the `latest` version is not a page attribute. 

Working off your recent PR I made the following modifications to meet my immediate needs.

https://github.com/Mogztter/antora-lunr/compare/issue-15-exclude-page...danyill:issue-25-index-latest

I can't really do a PR until we introduce some configuration to this extension.

I think it would be preferable to do this with a playbook key which `antora-lunr` then works with. Because Antora validates the playbook either Antora's validation needs to be relaxed or a schema has to be provided by the extension. I think it would be nice if we could hook into an `extensions` key in the playbook and declare `antora-lunr` and then provide a schema for it (like https://gitlab.com/antora/antora/blob/master/packages/playbook-builder/lib/config/schema.js) . But I have no idea how to implement that with my current skill level...

I was thinking of something like:

```yaml
  extensions: {
    'antora-lunr': {
      index: {
        doc: 'The html elements which should be indexed (default: article)',
        format: Array,
        default: undefined,
      },
      noindex: {
        doc: 'The html elements which should not be indexed (defaults: none)',
        format: Array,
        default: undefined,
      },
      versions: {
        doc: 'The versions which should be indexed, can use reserved keywords prerelease and latest',
        format: Array,
        default: undefined,
      },
    },
  }
```
