### ISSUE TITLE
The search box doesn't show up

### ISSUE THREAD

**Issue by ivanhjc** [Mogztter/antora-lunr#26]
After following the instructions in README to build the [official Antora doc](https://gitlab.com/antora/docs.antora.org) the site could be generated successfully without errors and the `search-index.js` file was generated successfully in the root directory, but I didn't see the search box in the UI. I don't understand this line in README "Copy the supplemental_ui directory in your Antora playbook repository and configure a supplemental_files". The supplemental_ui directory is already there. What place should I copy  it to?

**Comment by Mogztter** [comment]
In your Antora playbook repository/project you will need to copy the directory [supplemental_ui ](https://github.com/Mogztter/antora-lunr/tree/master/supplemental_ui).
Then add the key `supplemental_files` in your playbook:

```yml
ui:
  bundle:
    url: 'https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable'
    snapshot: true
  supplemental_files: './supplemental-ui'
```

Does it make sense ?
